### ISSUE TITLE
Automatic switching of headphones/speakers no longer works

### ISSUE THREAD

**Issue by atowler84** [blue-systems/netrunner-issues#3]
When I plug in headphones the audio output is no longer automatically switched to the headphones from the speakers. When I unplug the headphones I'm no longer automatically switched to the speakers.

**Comment by AJSlye** [comment]
Removing the comment from this line in /etc/pulse/default.pa should fix this issue:
#load-module module-switch-on-port-available

**Comment by atowler84** [comment]
I had already done that, actually, and it still wasn't working. I've just verified that the line is still uncommented.

**Comment by atowler84** [comment]
This appears to have been resolved in a recent update.
